language: ruby
rvm:
- 2.1

# before_install:
# - travis_retry gem install bitballoon
# - travis_retry gem install jekyll
# script: jekyll build
# after_success: bitballoon deploy frontend

# before_install:
# - travis_retry gem install jekyll
# - travis_retry gem install kramdown

# script:
#   - bundle exec jekyll build
#   - bundle exec htmlproof ./frontend --only-4xx --check-favicon --check-html

sudo: false
script: 
  - "set -e && gem install github-pages && jekyll build"
  # - "bundle exec jekyll --version"
  # - "bundle exec rspec"
  # - "bundle exec jekyll new frontend"
  # - "cd frontend && bundle exec jekyll build --watch --trace"

# branch whitelist
branches:
  only:
    - setup

notifications:
  email: "yannick.congo@gmail.com"

matrix:
  fast_finish: true

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer