language: ruby
rvm:
- 2.1

install: 
  - ls
  - cd vendor/
  - bundle install
after_success: bundle exec frontend push --headless
script: bundle exec jekyll build

# branch whitelist
branches:
  only:
    - setup

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of