language: ruby
rvm:
- 2.1

# before_install:
# - travis_retry gem install bitballoon
# - travis_retry gem install jekyll
# script: jekyll build
# after_success: bitballoon deploy frontend

script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html

# branch whitelist
branches:
  only:
    - setup

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer